# Default namespace for all resources deployed by this chart
namespace: development

# Redis
redis:
  image: redis:6
  port: 6379
  replicas: 1
  healthcheck:
    test: ["CMD", "redis-cli", "ping"]
    interval: "10s"
    timeout: "5s"
    retries: 5

# Volumes
volumes:
  redis_data:
    size: 10Gi