apiVersion: v2
name: observability-stack
description: A Helm chart for observability - Prometheus, Grafana, Loki, and Promtail
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: kube-prometheus-stack
    repository: "https://prometheus-community.github.io/helm-charts"
    version: "70.3.0"
