namespace: observability

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      image:
        tag: "v2.55.0"
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "1000m"
  grafana:
    image:
      tag: "11.5.2"
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          url: http://observability-loki:3100
          access: proxy
          isDefault: false

# Loki configurations
loki-stack:
  loki:
    enabled: true
    replicaCount: 2
    persistence:
      enabled: false
    config:
      auth_enabled: false
  promtail:
    enabled: true
    config:
      clients:
        - url: http://observability-loki:3100/loki/api/v1/push
      scrape_configs:
        - job_name: 'kubernetes-pods'
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_label_name]
              target_label: __service__
            - source_labels: [__meta_kubernetes_namespace]
              target_label: __namespace__