namespace: observability

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "1000m"

