apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-efs-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: {{ .Values.volumes.redis_data.size }}