apiVersion: v1
kind: Secret
metadata:
  name: loki-config
  namespace: observability
type: Opaque
data:
  loki-config.yaml: |
    YXV0aF9lbmFibGVkOiBmYWxzZQpzZXJ2ZXI6CiAgaHR0cF9saXN0ZW5fcG9ydDogMzEwMApzY2hlbWFfY29uZmlnOgogIGNvbmZpZ3M6CiAgICAtIGZyb206ICIyMDI0LTA0LTAxIgogICAgICBzdG9yZTogdHNkYgogICAgICBvYmplY3Rfc3RvcmU6IHMzCiAgICAgIHNjaGVtYTogdjEzCiAgICAgIGluZGV4OgogICAgICAgIHByZWZpeDogbG9raV9pbmRleF8KICAgICAgICBwZXJpb2Q6IDI0aApzdG9yYWdlX2NvbmZpZzoKICBhd3M6CiAgICByZWdpb246IHVzLWVhc3QtMQogICAgYnVja2V0bmFtZXM6IHNtLWxva2ktc3RvcmFnZS1idWNrZXQKICAgIHMzZm9yY2VwYXRoc3R5bGU6IGZhbHNlCmNvbXBhY3RvcjoKICByZXRlbnRpb25fZW5hYmxlZDogdHJ1ZQogIGRlbGV0ZV9yZXF1ZXN0X3N0b3JlOiBzMwoK

