auth_enabled: false
server:
  http_listen_port: 3100
schema_config:
  configs:
    - from: "2024-04-01"
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: loki_index_
        period: 24h
storage_config:
  aws:
    region: us-east-1
    bucketnames: sm-loki-storage-bucket
    s3forcepathstyle: false
compactor:
  retention_enabled: true
  delete_request_store: s3

