apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: status-page-venv-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volumes.status_page_venv.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-files-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volumes.static_files.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: efs-sc
  accessModes: 
     - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volumes.redis_data.size }}