apiVersion: v2
name: status-page-stack
description: A Helm chart for Status-Page application
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: kube-prometheus-stack
    repository: "https://prometheus-community.github.io/helm-charts"
    version: "45.0.0"
