apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DATABASE_PASSWORD: YWJjZGVmZ2gxMjM0NTYK
  DJANGO_SUPERUSER_PASSWORD: YWRtaW4xMjMK
